displayName=Group TCG
author=Sqwiglyy
description=Use OSRS TCG cards as solo or shared Bronzeman unlocks
tags=tcg,group,bronzeman,restriction,multiplayer,solo
plugins=com.groupmantcg.GroupmanTcgPlugin
version=0.1.1
build=standard
